# Generated by Django 4.2.21 on 2025-05-29 12:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_spanner


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(default=django_spanner.gen_rand_int64, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'People',
                'db_table': 'Person',
            },
        ),
        migrations.CreateModel(
            name='Follows',
            fields=[
                ('id', models.BigAutoField(default=django_spanner.gen_rand_int64, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('followed_person', models.ForeignKey(db_column='followed_person_id', on_delete=django.db.models.deletion.CASCADE, related_name='follower_relations', to='fingraph_app.person')),
                ('follower', models.ForeignKey(db_column='follower_person_id', on_delete=django.db.models.deletion.CASCADE, related_name='following_relations', to='fingraph_app.person')),
            ],
            options={
                'verbose_name_plural': 'Follows',
                'db_table': 'Follows',
                'unique_together': {('follower', 'followed_person')},
            },
        ),
    ]
